# render.yaml
services:
  - type: web
    name: invoicer-api
    runtime: docker
    plan: free
    region: frankfurt  # Или oregon, ohio
    branch: main
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: invoicer-db
          property: connectionString
    healthCheckPath: /__version__
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: false  # Мы будем деплоить через GitHub Actions

databases:
  - name: invoicer-db
    plan: free
    databaseName: invoicer
    user: invoicer
